version: '3'

services:

  rest-api:
    image: rest-api:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: rest_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rest_api
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: rest_api_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rest_api
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local
